const relativeDates = {
  today: '2026-10-08',
  yesterday: '2026-10-07',
  lastWeek: '2026-10-01',
  nextWeek: '2026-10-15',
}

export function createSeedData() {
  return {
    meta: {
      seedVersion: 2,
      createdAt: relativeDates.today,
      duplicateOperations: {},
    },
    accounts: [
      {
        id: 'acct-customer-amina',
        verified: true,
        role: 'customer',
        displayName: 'Amina Bello',
        email: 'amina.demo@example.test',
        profileId: 'profile-customer-amina',
      },
      {
        id: 'acct-customer-chidi',
        verified: false,
        role: 'customer',
        displayName: 'Chidi Okafor',
        email: 'chidi.demo@example.test',
        profileId: 'profile-customer-chidi',
      },
      {
        id: 'acct-designer-kemi',
        verified: true,
        role: 'designer',
        displayName: 'Kemi Atelier',
        email: 'kemi.demo@example.test',
        profileId: 'profile-designer-kemi',
        designerId: 'designer-kemi',
      },
      {
        id: 'acct-designer-bayo',
        verified: true,
        role: 'designer',
        displayName: 'Bayo Stitches',
        email: 'bayo.demo@example.test',
        profileId: 'profile-designer-bayo',
        designerId: 'designer-bayo',
      },
      {
        id: 'acct-designer-zara',
        verified: true,
        role: 'designer',
        displayName: 'Zara Heritage Studio',
        email: 'zara.demo@example.test',
        profileId: 'profile-designer-zara',
        designerId: 'designer-zara',
      },
      {
        id: 'acct-admin-tunde',
        verified: true,
        role: 'admin',
        displayName: 'Tunde Okafor',
        email: 'admin.demo@example.test',
        profileId: 'profile-admin-tunde',
      },
    ],
    profiles: [
      {
        id: 'profile-customer-amina',
        accountId: 'acct-customer-amina',
        role: 'customer',
        name: 'Amina Bello',
        contactPreference: 'in-app message',
        city: 'Lagos demo area',
      },
      {
        id: 'profile-customer-chidi',
        accountId: 'acct-customer-chidi',
        role: 'customer',
        name: 'Chidi Okafor',
        contactPreference: 'in-app message',
        city: 'Abuja demo area',
      },
      {
        id: 'profile-designer-kemi',
        accountId: 'acct-designer-kemi',
        role: 'designer',
        designerId: 'designer-kemi',
        businessName: 'Kemi Atelier',
        serviceLocation: 'Lagos Island demo area',
        specializations: ['aso ebi', 'bridal reception', 'agbada'],
        bio: 'Fictional studio for culturally relevant occasion outfits.',
        availability: 'accepting demo requests',
        publicationStatus: 'approved',
      },
      {
        id: 'profile-designer-bayo',
        accountId: 'acct-designer-bayo',
        role: 'designer',
        designerId: 'designer-bayo',
        businessName: 'Bayo Stitches',
        serviceLocation: 'Ibadan demo area',
        specializations: ['senator wear', 'kaftan'],
        bio: 'Demo menswear specialist pending administrator approval.',
        availability: 'reviewing availability',
        publicationStatus: 'pending',
      },
      {
        id: 'profile-designer-zara',
        accountId: 'acct-designer-zara',
        role: 'designer',
        designerId: 'designer-zara',
        businessName: 'Zara Heritage Studio',
        serviceLocation: 'Enugu demo area',
        specializations: ['traditional wrapper', 'occasion blouse'],
        bio: 'Suspended fictional profile kept for existing-record access only.',
        availability: 'not accepting new work',
        publicationStatus: 'suspended',
      },
      {
        id: 'profile-admin-tunde',
        accountId: 'acct-admin-tunde',
        role: 'admin',
        name: 'Tunde Okafor',
        adminScope: 'demo moderation',
      },
    ],
    designers: [
      {
        id: 'designer-kemi',
        accountId: 'acct-designer-kemi',
        profileId: 'profile-designer-kemi',
        status: 'approved',
        published: true,
        rating: 4.8,
      },
      {
        id: 'designer-bayo',
        accountId: 'acct-designer-bayo',
        profileId: 'profile-designer-bayo',
        status: 'pending',
        published: false,
        rating: null,
      },
      {
        id: 'designer-zara',
        accountId: 'acct-designer-zara',
        profileId: 'profile-designer-zara',
        status: 'suspended',
        published: false,
        rating: 4.1,
      },
    ],
    portfolios: [
      {
        id: 'portfolio-kemi-aso-ebi',
        designerId: 'designer-kemi',
        title: 'Emerald aso ebi set',
        status: 'published',
        category: 'aso ebi',
        imageState: 'available',
      },
      {
        id: 'portfolio-kemi-bridal',
        designerId: 'designer-kemi',
        title: 'Reception gown with gele styling',
        status: 'published',
        category: 'bridal reception',
        imageState: 'temporary-unavailable',
      },
      {
        id: 'portfolio-bayo-kaftan',
        designerId: 'designer-bayo',
        title: 'Demo kaftan sample',
        status: 'unpublished',
        category: 'kaftan',
        imageState: 'available',
      },
    ],
    requests: [
      {
        id: 'request-submitted-amina',
        customerId: 'acct-customer-amina',
        designerId: 'designer-kemi',
        title: 'Family introduction outfit',
        state: 'submitted',
        measurementStatus: 'pending',
        createdAt: relativeDates.yesterday,
      },
      {
        id: 'request-discussing-amina',
        customerId: 'acct-customer-amina',
        designerId: 'designer-kemi',
        title: 'Civil wedding reception dress',
        state: 'discussing',
        measurementStatus: 'reviewed',
        createdAt: relativeDates.lastWeek,
      },
      {
        id: 'request-awaiting-confirmation-chidi',
        customerId: 'acct-customer-chidi',
        designerId: 'designer-kemi',
        title: 'Festival agbada',
        state: 'awaiting-confirmation',
        measurementStatus: 'complete',
        createdAt: relativeDates.lastWeek,
      },
      {
        id: 'request-declined-amina',
        customerId: 'acct-customer-amina',
        designerId: 'designer-bayo',
        title: 'Short-notice kaftan',
        state: 'declined',
        measurementStatus: 'not-started',
        createdAt: relativeDates.lastWeek,
      },
      {
        id: 'request-withdrawn-chidi',
        customerId: 'acct-customer-chidi',
        designerId: 'designer-zara',
        title: 'Cultural dinner outfit',
        state: 'withdrawn',
        measurementStatus: 'pending',
        createdAt: relativeDates.lastWeek,
      },
      {
        id: 'request-converted-amina',
        customerId: 'acct-customer-amina',
        designerId: 'designer-kemi',
        title: 'Engagement ceremony attire',
        state: 'converted-to-order',
        measurementStatus: 'reviewed',
        createdAt: relativeDates.lastWeek,
        orderId: 'order-amina-engagement',
      },
    ],
    measurements: [
      {
        id: 'measurement-amina-occasionwear',
        customerId: 'acct-customer-amina',
        category: 'occasionwear demo set',
        unit: 'cm',
        status: 'reviewed',
        values: { bust: 92, waist: 76, hip: 104 },
      },
      {
        id: 'measurement-chidi-menswear',
        customerId: 'acct-customer-chidi',
        category: 'menswear demo set',
        unit: 'cm',
        status: 'complete',
        values: { chest: 104, waist: 90, sleeve: 63 },
      },
    ],
    conversations: [
      {
        id: 'thread-request-discussing-amina',
        requestId: 'request-discussing-amina',
        participantIds: ['acct-customer-amina', 'acct-designer-kemi'],
        updatedAt: relativeDates.today,
        lastMessagePreview: 'I will attach the lace reference in the request.',
      },
      {
        id: 'thread-order-amina-engagement',
        orderId: 'order-amina-engagement',
        participantIds: ['acct-customer-amina', 'acct-designer-kemi'],
        updatedAt: relativeDates.yesterday,
        lastMessagePreview: 'Ready for handover on the agreed date.',
      },
    ],
    messages: [
      {
        id: 'msg-001',
        threadId: 'thread-request-discussing-amina',
        senderId: 'acct-customer-amina',
        body: 'Can the sleeves be less fitted?',
        sentAt: '2026-10-08T09:00:00+01:00',
      },
      {
        id: 'msg-002',
        threadId: 'thread-request-discussing-amina',
        senderId: 'acct-designer-kemi',
        body: 'Yes, I will reflect that in the next specification.',
        sentAt: '2026-10-08T09:15:00+01:00',
      },
    ],
    specifications: [
      {
        id: 'spec-request-discussing-v1',
        requestId: 'request-discussing-amina',
        version: 1,
        status: 'draft',
        proposedBy: 'acct-designer-kemi',
        createdAt: relativeDates.today,
        terms: {
          garment: 'Reception dress',
          fabricResponsibility: 'customer supplies fabric',
          agreedPriceLabel: 'NGN demo amount pending real commercial contract',
        },
      },
      {
        id: 'spec-request-awaiting-v1',
        requestId: 'request-awaiting-confirmation-chidi',
        version: 1,
        status: 'superseded',
        proposedBy: 'acct-designer-kemi',
        createdAt: relativeDates.lastWeek,
        terms: {
          garment: 'Agbada set',
          fabricResponsibility: 'designer sources fabric',
          agreedPriceLabel: 'NGN demo amount pending real commercial contract',
        },
      },
      {
        id: 'spec-request-awaiting-v2',
        requestId: 'request-awaiting-confirmation-chidi',
        version: 2,
        status: 'awaiting-customer-confirmation',
        proposedBy: 'acct-designer-kemi',
        createdAt: relativeDates.yesterday,
        terms: {
          garment: 'Agbada set with cap',
          fabricResponsibility: 'designer sources fabric',
          agreedPriceLabel: 'NGN demo amount pending real commercial contract',
        },
      },
    ],
    orders: [
      {
        id: 'order-amina-engagement',
        requestId: 'request-converted-amina',
        customerId: 'acct-customer-amina',
        designerId: 'designer-kemi',
        status: 'in-production',
        acceptedSpecId: 'spec-order-amina-v1',
        snapshot: {
          title: 'Engagement ceremony attire',
          garment: 'Aso oke dress and gele',
          agreedDate: relativeDates.nextWeek,
          commercialTerms: 'Demo terms only. No payment or escrow is simulated.',
        },
        progressHistory: [
          {
            id: 'progress-001',
            status: 'confirmed',
            actorId: 'acct-customer-amina',
            at: relativeDates.lastWeek,
          },
          {
            id: 'progress-002',
            status: 'in-production',
            actorId: 'acct-designer-kemi',
            at: relativeDates.yesterday,
          },
        ],
      },
    ],
    notifications: [
      {
        id: 'notification-amina-spec',
        ownerId: 'acct-customer-amina',
        title: 'Specification update available',
        destination: '/customer/requests-orders',
        read: false,
      },
      {
        id: 'notification-kemi-request',
        ownerId: 'acct-designer-kemi',
        title: 'New demo request received',
        destination: '/designer/requests-orders',
        read: false,
      },
    ],
    reviews: [
      {
        id: 'review-kemi-amina',
        orderId: 'order-amina-engagement',
        designerId: 'designer-kemi',
        customerId: 'acct-customer-amina',
        rating: 5,
        body: 'Fictional review for completed-order display later.',
        status: 'published',
      },
    ],
    issues: [
      {
        id: 'issue-order-amina-fit',
        orderId: 'order-amina-engagement',
        reporterId: 'acct-customer-amina',
        assigneeId: 'acct-admin-tunde',
        status: 'open',
        title: 'Sleeve fit review requested',
        resolution: null,
      },
    ],
  }
}
